apiVersion: "spec.keptn.sh/0.2.3"
kind: Shipyard
metadata:
  name: "shipyard-echo-service"
spec:
  stages:
    - name: "first-stage"
      sequences:
        - name: "mysequence"
          tasks:
            - name: "echo"
    - name: "second-stage"
      sequences:
        - name: "mysequence"
          triggeredOn:
            - event: "first-stage.mysequence.finished"
          tasks:
            - name: "echo"
            - name: "echo"  
