apiVersion: "spec.keptn.sh/0.2.3"
kind: Shipyard
metadata:
  name: "shipyard-echo-service"
spec:
  stages:
    - name: "first-stage"
      sequences:
        - name: "mysequence"
          tasks:
            - name: "1-echo-mysequence-first-stage"
    - name: "second-stage"
      sequences:
        - name: "mysequence"
          triggeredOn:
            - event: "first-stage.mysequence.finished"
          tasks:
            - name: "1-echo-mysequence-second-stage"
            - name: "2-echo-mysequence-second-stage"  
